<?php

namespace Cmhelp\Utils;

class OsxVirtualHostManager extends VirtualHostManager
{

    /**
     * @param $name
     */
    public function addVirtualHost($name)
    {
        parent::addVirtualHost($name); // TODO: Change the autogenerated stub
    }


    /**
     * @inheritDoc
     */
    protected function generateVirtualHostContent($name)
    {
        return null;
    }
}